apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-portal-ui
  name: data-portal-ui
spec:
  type: ClusterIP
  ports:
  - name: http-web
    port: 8080
    targetPort: 8080
  selector:
    app: data-portal-ui
