apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-portal-ui
  name: data-portal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-portal-ui
  template:
    metadata:
      labels:
        app: data-portal-ui
        version: 1-dev
    spec:
      containers:
      - env:
        - name: DATA_PORTAL_UI_HOST
          value: 0.0.0.0
        - name: DATA_PORTAL_UI_PORT
          value: "8080"
        - name: DATA_PORTAL_UI_SVC_REPOSITORY_URL
          value: /api/repository
        - name: DATA_PORTAL_UI_SVC_SEARCH_URL
          value: /api/search
        image: ghga/data-portal-ui:0.0.0-132-412680c-main
        name: data-portal-ui
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes: null
