apiVersion: v1
kind: Service
metadata:
  name: ghga-drs3
  labels:
    category: ghga-drs3
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: drs3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drs3
  labels:
    app: drs3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drs3
data:
  .drs3.yaml: |
    api_root_path: /
    api_route: /ga4gh/drs/v1/
    auto_reload: true
    aws_config_ini: null
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    db_print_logs: false
    docs_url: /docs
    host: 0.0.0.0
    log_level: info
    openapi_url: /openapi.json
    port: 8080
    rabbitmq_host: rabbitmq
    rabbitmq_port: 5672
    s3_session_token: null
    service_name: drs3
    topic_name_drs_object_registered: drs-object-registered
    topic_name_file_registered: file-internally-registered
    topic_name_file_staged: file_staged_for_download
    topic_name_stage_request: non_staged_file_requested
    workers: 1
