apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-search
  name: metadata-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-search
  template:
    metadata:
      labels:
        app: metadata-search
        version: 1-dev
    spec:
      containers:
      - env:
        - name: METADATA_SEARCH_SERVICE_API_ROOT_PATH
          value: /api/search
        - name: METADATA_SEARCH_SERVICE_DB_NAME
          value: metadata-db
        - name: METADATA_SEARCH_SERVICE_DB_URL
          value: mongodb://mongodb
         #value: mongodb://metadata-db-access-svc
         #value: mongodb://metadata-db
        - name: METADATA_SEARCH_SERVICE_HOST
          value: 0.0.0.0
        image: ghga/metadata-search-service:0.0.0-19-17407a9-main
        name: metadata-search
        ports:
        - containerPort: 8080
