apiVersion: v1
kind: Service
metadata:
  name: metadata-catalogue
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      targetPort: 8080
  selector:
    app: metadata-catalogue
