apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-catalogue
  name: metadata-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-catalogue
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app: metadata-catalogue
    spec:
      containers:
        - env:
            - name: METADATA_CATALOGUE_HOST
              value: 0.0.0.0
            - name: METADATA_CATALOGUE_PORT
              value: "8080"
            - name: METADATA_CATALOGUE_SVC_SEARCH_URL
              value: /api/search
            - name: METADATA_CATALOGUE_SVC_REPOSITORY_URL
              value: /api/repository
          image: ghga/metadata-catalogue:0.0.0-9-da4e8bf-main
          name: metadata-catalogue
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
