apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-cert: "secret/nginx/"
        vault.hashicorp.com/agent-inject-template-cert: |
          {{- with secret "secret/nginx/blob" -}}
           {{ .Data.cert }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-blob: "secret/nginx/"
        vault.hashicorp.com/agent-inject-template-blob: |
          {{- with secret "secret/nginx/blob" -}}
           {{ .Data.pass }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-key: "secret/nginx/"
        vault.hashicorp.com/agent-inject-template-key: |
          {{- with secret "secret/nginx/blob" -}}
           {{ .Data.key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ssl: "secret/nginx/"
        vault.hashicorp.com/agent-inject-template-ssl: |
          {{- with secret "secret/nginx/blob" -}}
           {{ .Data.sslparam }}
          {{- end }}
        vault.hashicorp.com/role: "nginx-role"
      labels:
        app: nginx
        version: 1-dev
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: nginxsecretconfigmap
      - name: configmap-volume-cat
        configMap:
          name: nginxsecretconfigmapcatalog
      serviceAccountName: nginx
      containers:
      - name: nginxhttps
        image: nginxinc/nginx-unprivileged:1.20
        ports:
        - containerPort: 8443
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          subPath: hd-dev.ghga-dev.de.conf
          name: configmap-volume
        - mountPath: /etc/nginx/conf.d
          subPath: hd-catalog.-ghga-dev.de.conf
          name: configmap-volume-cat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  labels:
    app: nginx
