apiVersion: v1
data:
  hd-catalog.ghga-dev.de.conf: |
    server {
        server_name hd-catalog.ghga-dev.de;
        
         auth_basic           "Please authenticate";
         auth_basic_user_file /vault/secrets/blob;
         
        client_max_body_size 4g;

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass http://metadata-catalogue.catalogue.svc.cluster.local:8080;
        }
        location  /api/search {
            rewrite /api/search/(.*) /$1  break;
            proxy_pass         http://metadata-search-svc.catalogue.svc.cluster.local:8080;
            proxy_redirect     off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
        }
        
        location  /api/repository {
            rewrite /api/repository/(.*) /$1  break;
            proxy_pass         http://metadata-rep.catalogue.svc.cluster.local:8080;
            proxy_redirect     off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
        }

        listen [::]:8443 ssl ipv6only=on;
        listen 8443 ssl;
        ssl_certificate /vault/secrets/cert;
        ssl_certificate_key /vault/secrets/key;



        ssl_session_cache shared:le_nginx_SSL:1m;
        ssl_session_timeout 1440m;

        # intermediate configuration
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
        add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_dhparam /vault/secrets/ssl;

    }
    server {
        if ($host = hd-catalog.ghga-dev.de) {
            return 301 https://$host$request_uri;
        }


        listen 8080 default_server;
        listen [::]:8080 default_server;

        server_name hd-catalog.ghga-dev.de;
        return 404;
    }
   
kind: ConfigMap
metadata:
  name: nginxsecretconfigmapcatalog
