apiVersion: v1
kind: Service
metadata:  
  labels:
    app: nginx-secret
  name: nginxsvc 
spec:  
  ports:
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32080
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
