apiVersion: v1
kind: Service
metadata:  
  labels:
    app: nginx
  name: nginxsvc 
spec:  
  ports:
  - name: http
    nodePort: 32070
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32080
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
