apiVersion: v1
kind: ConfigMap
metadata:
  name: ucs
data:
  .ucs.yaml: |
        api_root_path: /api/ucs
        auto_reload: false
        aws_config_ini: null
        cors_allow_credentials: null
        cors_allowed_headers: null
        cors_allowed_methods: null
        cors_allowed_origins: null
        db_print_logs: false
        docs_url: /docs
        host: 0.0.0.0
        log_level: info
        openapi_url: /openapi.json
        port: 8080
        rabbitmq_host: rabbitmq
        rabbitmq_port: 5672
        s3_session_token: null
        service_name: upload_controller_service
        topic_new_study: new_study_created
        topic_upload_received: file_upload_received
        workers: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ghga-ucs
  labels:
    category: ghga-ucs
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ucs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ucs
  labels:
   app: ucs
