apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blobfish-ui
  name: blobfish-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blobfish-ui
  template:
    metadata:
      labels:
        app: blobfish-ui
    spec:
      containers:
      - env:
        - name: DATA_PORTAL_UI_V1_HOST
          value: 0.0.0.0
        - name: DATA_PORTAL_UI_V1_PORT
          value: "8080"
        - name: DATA_PORTAL_UI_V1_SVC_REPOSITORY_URL
          value: /api/repository
        - name: DATA_PORTAL_UI_V1_SVC_SEARCH_URL
          value: /api/search
        image: ghga/data_portal_ui_v1:dev
        name: blobfish-ui
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes: null
