apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: metadata-repository-pvc
  name: metadata-repository-pvc
spec:
  storageClassName: csi-sc-cinderplugin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
