apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-repository
  name: metadata-repository
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: metadata-repository
