apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: metadata-db-fs
  name: metadata-db-fs
spec:
  storageClassName: csi-sc-cinderplugin
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
