apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
           secretName: nginx-certs-keys
      - name: auth-tokens
        secret:
           secretName: auth-pass
      - name: configmap-volume
        configMap:
          name: nginxconfigmap 
      containers:
      - name: nginxhttps
        image: nginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        - mountPath: /etc/nginx/auth
          name: auth-tokens 

