name: Update App Version of A Deployment
on:
  repository_dispatch: {}

  # Usage:
  # curl -X POST https://api.github.com/repos/<name_of_account>/<name_of_repo>/dispatches \
  #  -H 'Accept: application/vnd.github.everest-preview+json' \
  #  -u ${{ secrets.ACCESS_TOKEN }} \ # access token needs to be of format: <username>:<personal_access_token>
  #  --data '{"event_type": "new_app_version", "client_payload": { "app_name": "name_of_app", "new_app_version": "new_app_version" }}'

jobs:
  updateVersion:
    if: github.event.action == 'new_app_version'
    runs-on: ubuntu-latest
    env:
      APP_YAML: "./blobfish/${{ github.event.client_payload.app_name }}-deployment.yaml"
      NEW_APP_VERSION: "${{ github.event.client_payload.new_app_version }}"
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Replace image tag in deployment yaml
      run: |
        sed -i \
          "s/^image:.*$/image: \"${NEW_APP_VERSION}\"/" \
          "${APP_YAML}"             
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop
        message: 'update app version of chart \"${{ github.event.client_payload.app_name }}\" to ${{ github.event.client_payload.new_app_version }}'
